# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49d5bc30eb07f8b6af6417ce1004b4f31a06f7370ec7c1bf574def80a912718df42b73d737d0702cbc17367b8930d0f3354f2c0d68206af14d7493f6e347f3c7

test:
  secret_key_base: 638b3a6cb5210d308036aa4080e3786c7f8ae1c51d5892f75bf8cafa66c3d3a14439753e3283da8c9604824c712893ccb2a9bbc2731f683cffcd4069db08dced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
